# -*- coding: utf-8 -*-

ACCESS_METHOD_SSH = 0
ACCESS_METHOD_TELNET = 1
ACCESS_METHOD_API = 2

ACCESS_METHOD = (
    (ACCESS_METHOD_SSH,'SSH'),
    (ACCESS_METHOD_TELNET,'TELNET'),
    (ACCESS_METHOD_API,'API'),
)
